export const DataItem = [
  {
    id: 1,
    name: 'TURQUOISE',
    code: '#1abc9c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 2,
    name: 'EMERALD',
    code: '#2ecc71',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 3,
    name: 'PETER RIVER',
    code: '#3498db',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 4,
    name: 'AMETHYST',
    code: '#9b59b6',
    img: require('../../../assets/images/e43_Good-Day_South-Korea.png'),
  },
  {
    id: 5,
    name: 'WET ASPHALT',
    code: '#34495e',
    img: require('../../../assets/images/The-Funkees_Mimbo_Nigeria.png'),
  },
  {
    id: 6,
    name: 'GREEN SEA',
    code: '#16a085',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 7,
    name: 'NEPHRITIS',
    code: '#27ae60',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 7,
    name: 'BELIZE HOLE',
    code: '#2980b9',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 8,
    name: 'WISTERIA',
    code: '#8e44ad',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 9,
    name: 'MIDNIGHT BLUE',
    code: '#2c3e50',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 10,
    name: 'SUN FLOWER',
    code: '#f1c40f',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 11,
    name: 'CARROT',
    code: '#e67e22',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 12,
    name: 'ALIZARIN',
    code: '#e74c3c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 13,
    name: 'CLOUDS',
    code: '#ecf0f1',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 14,
    name: 'CONCRETE',
    code: '#95a5a6',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 15,
    name: 'ORANGE',
    code: '#f39c12',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 16,
    name: 'PUMPKIN',
    code: '#d35400',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 17,
    name: 'POMEGRANATE',
    code: '#c0392b',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 18,
    name: 'SILVER',
    code: '#bdc3c7',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 19,
    name: 'ASBESTOS',
    code: '#7f8c8d',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 20,
    name: 'TURQUOISE',
    code: '#1abc9c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 21,
    name: 'EMERALD',
    code: '#2ecc71',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 22,
    name: 'PETER RIVER',
    code: '#3498db',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 23,
    name: 'AMETHYST',
    code: '#9b59b6',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 24,
    name: 'WET ASPHALT',
    code: '#34495e',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 25,
    name: 'GREEN SEA',
    code: '#16a085',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 26,
    name: 'NEPHRITIS',
    code: '#27ae60',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 27,
    name: 'BELIZE HOLE',
    code: '#2980b9',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 28,
    name: 'WISTERIA',
    code: '#8e44ad',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 29,
    name: 'MIDNIGHT BLUE',
    code: '#2c3e50',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 30,
    name: 'SUN FLOWER',
    code: '#f1c40f',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 31,
    name: 'CARROT',
    code: '#e67e22',
    img: require('../../../assets/images/MC-Solar_Comme-Dans-Un-Film_France.jpg'),
  },
  {
    id: 32,
    name: 'ALIZARIN',
    code: '#e74c3c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 33,
    name: 'CLOUDS',
    code: '#ecf0f1',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 34,
    name: 'CONCRETE',
    code: '#95a5a6',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 35,
    name: 'ORANGE',
    code: '#f39c12',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 36,
    name: 'PUMPKIN',
    code: '#d35400',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 37,
    name: 'POMEGRANATE',
    code: '#c0392b',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 38,
    name: 'SILVER',
    code: '#bdc3c7',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 39,
    name: 'ASBESTOS',
    code: '#7f8c8d',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 40,
    name: 'TURQUOISE',
    code: '#1abc9c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 41,
    name: 'EMERALD',
    code: '#2ecc71',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 42,
    name: 'PETER RIVER',
    code: '#3498db',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 43,
    name: 'AMETHYST',
    code: '#9b59b6',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 44,
    name: 'WET ASPHALT',
    code: '#34495e',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 45,
    name: 'GREEN SEA',
    code: '#16a085',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 46,
    name: 'NEPHRITIS',
    code: '#27ae60',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 47,
    name: 'BELIZE HOLE',
    code: '#2980b9',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 48,
    name: 'WISTERIA',
    code: '#8e44ad',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 49,
    name: 'MIDNIGHT BLUE',
    code: '#2c3e50',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 50,
    name: 'SUN FLOWER',
    code: '#f1c40f',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 51,
    name: 'CARROT',
    code: '#e67e22',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 52,
    name: 'ALIZARIN',
    code: '#e74c3c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 53,
    name: 'CLOUDS',
    code: '#ecf0f1',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 54,
    name: 'TURQUOISE',
    code: '#1abc9c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 55,
    name: 'EMERALD',
    code: '#2ecc71',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 56,
    name: 'PETER RIVER',
    code: '#3498db',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 57,
    name: 'AMETHYST',
    code: '#9b59b6',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 58,
    name: 'WET ASPHALT',
    code: '#34495e',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 59,
    name: 'GREEN SEA',
    code: '#16a085',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 60,
    name: 'NEPHRITIS',
    code: '#27ae60',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 61,
    name: 'BELIZE HOLE',
    code: '#2980b9',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 62,
    name: 'WISTERIA',
    code: '#8e44ad',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 63,
    name: 'MIDNIGHT BLUE',
    code: '#2c3e50',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 64,
    name: 'SUN FLOWER',
    code: '#f1c40f',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 65,
    name: 'CARROT',
    code: '#e67e22',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 66,
    name: 'ALIZARIN',
    code: '#e74c3c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 67,
    name: 'CLOUDS',
    code: '#ecf0f1',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 68,
    name: 'CONCRETE',
    code: '#95a5a6',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 69,
    name: 'ORANGE',
    code: '#f39c12',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 70,
    name: 'PUMPKIN',
    code: '#d35400',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 71,
    name: 'POMEGRANATE',
    code: '#c0392b',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 72,
    name: 'SILVER',
    code: '#bdc3c7',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 73,
    name: 'ASBESTOS',
    code: '#7f8c8d',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 74,
    name: 'TURQUOISE',
    code: '#1abc9c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 75,
    name: 'EMERALD',
    code: '#2ecc71',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 76,
    name: 'PETER RIVER',
    code: '#3498db',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 77,
    name: 'AMETHYST',
    code: '#9b59b6',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 78,
    name: 'WET ASPHALT',
    code: '#34495e',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 79,
    name: 'GREEN SEA',
    code: '#16a085',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 80,
    name: 'NEPHRITIS',
    code: '#27ae60',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 81,
    name: 'BELIZE HOLE',
    code: '#2980b9',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 82,
    name: 'WISTERIA',
    code: '#8e44ad',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 83,
    name: 'MIDNIGHT BLUE',
    code: '#2c3e50',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 84,
    name: 'SUN FLOWER',
    code: '#f1c40f',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 85,
    name: 'CARROT',
    code: '#e67e22',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 86,
    name: 'ALIZARIN',
    code: '#e74c3c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 87,
    name: 'CLOUDS',
    code: '#ecf0f1',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 88,
    name: 'CONCRETE',
    code: '#95a5a6',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 89,
    name: 'ORANGE',
    code: '#f39c12',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 90,
    name: 'PUMPKIN',
    code: '#d35400',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 91,
    name: 'POMEGRANATE',
    code: '#c0392b',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 92,
    name: 'SILVER',
    code: '#bdc3c7',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 93,
    name: 'ASBESTOS',
    code: '#7f8c8d',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 94,
    name: 'TURQUOISE',
    code: '#1abc9c',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 95,
    name: 'EMERALD',
    code: '#2ecc71',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 96,
    name: 'PETER RIVER',
    code: '#3498db',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 97,
    name: 'AMETHYST',
    code: '#9b59b6',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 98,
    name: 'WET ASPHALT',
    code: '#34495e',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 99,
    name: 'GREEN SEA',
    code: '#16a085',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  {
    id: 100,
    name: 'NEPHRITIS',
    code: '#27ae60',
    img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  },
  // {
  //   name: 'BELIZE HOLE',
  //   code: '#2980b9',
  //   img: require('../../../assets/images/Tell_Floating-Lands_Belgium.jpg'),
  // },
  // {
  //   name: 'WISTERIA',
  //   code: '#8e44ad',
  //   img: require('../../../assets/images/Toxe_Determina_Sweden.png'),
  // },
  // {
  //   name: 'MIDNIGHT BLUE',
  //   code: '#2c3e50',
  //   img: require('../../../assets/images/Toxe_Determina_Sweden.png'),
  // },
  // {
  //   name: 'SUN FLOWER',
  //   code: '#f1c40f',
  //   img: require('../../../assets/images/Toxe_Determina_Sweden.png'),
  // },
  // {
  //   name: 'CARROT',
  //   code: '#e67e22',
  //   img: require('../../../assets/images/Toxe_Determina_Sweden.png'),
  // },
  // {
  //   name: 'ALIZARIN',
  //   code: '#e74c3c',
  //   img: require('../../../assets/images/Toxe_Determina_Sweden.png'),
  // },
  // {
  //   name: 'CLOUDS',
  //   code: '#ecf0f1',
  //   img: require('../../../assets/images/Toxe_Determina_Sweden.png'),
  // },
  // {
  //   name: 'ALIZARIN',
  //   code: '#e74c3c',
  //   img: require('../../../assets/images/Toxe_Determina_Sweden.png'),
  // },
  // {
  //   name: 'CLOUDS',
  //   code: '#ecf0f1',
  //   img: require('../../../assets/images/Toxe_Determina_Sweden.png'),
  // },
];
